### ISSUE TITLE
Image link please

### ISSUE THREAD

**Issue by ajsya** [NilsTheBest/ChairOfRepublic#2]
Hey Nils, where did you get the background image that you used in the studio thumbnail and forum banner? Could I have it?

**Comment by NilsTheBest** [comment]
![CookiePile](https://user-images.githubusercontent.com/41824646/62843895-b4d1cd00-bcbd-11e9-9463-e8988f7b5ef8.png)

**Comment by ajsya** [comment]
Okay thanks
